let g:macvim_skip_cmd_opt_movement = 1

set bg=dark

if has("gui_running")
  try
    colorscheme japanesque
  catch
  endtry

  set guifontwide=SourceHanCodeJP-Regular:h14
  set guifont=Fantasque\ Sans\ Mono\ Regular:h14
  set tranparency=15
endif
