" vim:set et foldmethod=marker:

let g:colorscheme_name = 'desert'

runtime config/base.vim
runtime config/autocmd.vim
runtime config/neobundle.vim
runtime config/plugins.vim
runtime config/tab.vim
runtime config/key.vim
runtime config/command.vim

set bg=dark
execute 'colorscheme ' . g:colorscheme_name
