" vim:set et foldmethod=marker:

let did_load_filetypes = 1

runtime rc/base.vim
runtime rc/autocmd.vim
runtime rc/neobundle.vim
runtime rc/tab.vim
runtime rc/key.vim
runtime rc/command.vim

if !has('vim_starting')
  echomsg '---> Reload bundles'
  call neobundle#call_hook('on_source')
endif
