source :rubygems

gem 'json'
gem 'rake'

gem 'bundler'

gem 'capistrano'
gem 'capistrano_colors'

gem 'pry'
gem 'pry-doc'

gem 'heroku'

gem 'powder'

# Rubygems support
gem 'gem-src'
gem 'rubygems-auto-rehash'
