(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
    (let* ((my-lisp-dir "~/.emacs.d/site-lisp/")
	   (default-directory my-lisp-dir))
      (setq load-path (cons my-lisp-dir load-path))
      (normal-top-level-add-subdirs-to-load-path)))
(if (fboundp 'normal-top-level-add-subdirs-to-load-path)
    (let* ((my-lisp-dir "~/.emacs.d/auto-install/")
	   (default-directory my-lisp-dir))
      (setq load-path (cons my-lisp-dir load-path))
      (normal-top-level-add-subdirs-to-load-path)))
(setenv "LANG" "en-US.UTF-8")

(require 'auto-install)

(set-default-coding-systems 'utf-8)
(setq current-language-environment "Japanese")
(column-number-mode t)
(setq completion-ignore-case t)
(setq make-backup-files nil)
(global-font-lock-mode t)
(setq inhibit-startup-messages t)
(global-set-key "\C-h" 'delete-backward-char)
(delete-selection-mode 1)
(setq kill-whole-line t)
(icomplete-mode nil)
(transient-mark-mode t)

(when (= emacs-major-version 22)
  (setq hc-ctrl-x-c-is-completion t)
  (require 'highlight-completion)
  (highlight-completion-mode 1)
  (global-set-key "\C-\\" 'toggle-input-method))

(iswitchb-mode 1)
(show-paren-mode 1)
(setq show-paren-style 'mixed)
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
(setq display-time-24hr-format t)
(setq display-time-day-and-date t)
(setq display-time-string-forms
      '(month "/" day " " 24-hours ":" minutes " "))
(display-time-mode 1)

(fset 'yes-or-no-p 'y-or-n-p)
(setq truncate-lines t)
(setq truncate-partial-width-windows nil)
(add-hook 'after-save-hook
	  'executable-make-buffer-file-executable-if-script-p)
(global-set-key "\C-m" 'newline-add-indent)
(when (boundp 'show-trailing-whitespace)
  (setq-default show-trailing-whitespace t))

(set-frame-parameter (selected-frame) 'alpha '(85 80))