(setenv "LANG" "ja_JP.UTF-8")
(add-to-list 'exec-path "/usr/local/bin")
(add-to-list 'load-path "~/.emacs.d/site-lisp")

(when (require 'auto-install nil t)
  (setq auto-install-directory "~/.emacs.d/auto-install")
  (auto-install-update-emacswiki-package-name t)
  (auto-install-compatibility-setup))
(require 'init-loader)
(when (require 'package nil t)
  (add-to-list 'package-archives
               '("marmalade" . "http://marmalade-repo.org/packages/"))
  (add-to-list 'package-archives
               '("ELPA" . "http://tromey.com/elpa/"))
  (package-initialize))

(set-default-coding-systems 'utf-8)
(column-number-mode t)
(line-number-mode t)
(size-indication-mode t)
(display-time-mode t)
(display-battery-mode t)
(setq current-language-environment "Japanese")
(setq completion-ignore-case t)
(setq make-backup-files nil)
(setq inhibit-startup-messages t)
(setq kill-whole-line t)
(global-font-lock-mode t)
(global-set-key "\C-h" 'delete-backward-char)
(delete-selection-mode 1)
(icomplete-mode nil)
(transient-mark-mode t)

(when (= emacs-major-version 22)
  (setq hc-ctrl-x-c-is-completion t)
  (require 'highlight-completion)
  (highlight-completion-mode 1)
  (global-set-key "\C-\\" 'toggle-input-method))

(iswitchb-mode 1)
(show-paren-mode 1)
(setq show-paren-style 'mixed)
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
(setq display-time-24hr-format t)
(setq display-time-day-and-date t)
(setq display-time-string-forms
  '(month "/" day " " 24-hours ":" minutes " "))
(display-time-mode 1)

(fset 'yes-or-no-p 'y-or-n-p)
(setq truncate-lines t)
(setq truncate-partial-width-windows nil)
(add-hook 'after-save-hook
  'executable-make-buffer-file-executable-if-script-p)
(when (boundp 'show-trailing-whitespace)
  (setq-default show-trailing-whitespace t))

(set-frame-parameter (selected-frame) 'alpha '(85 80))

(setq-default tab-width 2)
(setq-default indent-tabs-mode nil)
